### ISSUE TITLE
Height problem using rxvt shell

### ISSUE THREAD

**Issue by Fale** [awslabs/aws-shell#99]
I use both xterm and rxvt (rxvt-unicode-256color-ml version 9.21-6 from Fedora23 repositories).

In xterm everything is fine, while in rxvt, the shell starts being only 8 lines height. More you use it, more it grows, but it's a pretty annoying thing

**Comment by jefbed** [comment]
I've encountered similar in my project, jbxvt.  This is due to invalid struct termios flags being set, particularly member c_cflag not containing baud rate specification, |= B9600.  This is a bug in the original rxvt sources, likely carried to rxvt-unicode.  In the rxvt-unicode source, try changing line 601 of main.C to 
tio->c_cflag = (CS8 | CREAD|B9600);

I hope this helps.

**Comment by joguSD** [comment]
@Fale are you still having issues with this? 
To be honest though, I'm not sure how much we would be able to do here. This may be fixable upstream in `prompt-toolkit` though.

**Comment by Fale** [comment]
It seems like updating to Fedora 26 solved the problem. Probably the urxvt team or the prompt-toolkit one have fixed it :)
